# Shopify App Configuration
# Run `npx shopify app deploy` after editing scopes.

client_id = "$SHOPIFY_CLIENT_ID"

[access_scopes]
scopes = "read_channels,write_channels,read_files,write_files,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_online_store_navigation,write_online_store_navigation,read_products,write_products,read_publications,write_publications,read_content,write_content,read_themes,write_themes,read_translations,write_translations,read_orders,write_orders,read_webhooks,write_webhooks"
